name: "1. Build"

on:
  push:
    branches:
      - "*"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  buildPack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🚀 Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: 🚀 Install Dependencies
        run: yarn install --frozen-lockfile

      - name: 🚀 Build Typescript
        run: yarn _build

      - name: 🚀 Commit packed js
        id: commitPackedJs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          mkdir _dist
          mv ./dist ./_dist
          cp ./package.json ./_dist
          cp ./yarn.lock ./_dist

          git add ./_dist
          git commit -m "By GH-Actions"

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_dist
          publish_branch: production-build
          force_orphan: true
